name: ESLint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Prettier
        run: npx prettier --write .
  eslint:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
